name: Create PR on File Change

# Define triggers for the workflow:
on:
  workflow_dispatch: # Allows manual triggering from the GitHub UI
  schedule:
    # Runs every Wednesday at 02:45 AM (UTC)
    - cron: '45 2 * * 3'

jobs:
  run_script_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Extract cds-typer --help text
        run: node .github/typer/grab-typer-synopsis.js

      - name: Check for changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          if git diff --cached --exit-code; then
            echo "No changes detected. Exiting."
            exit 0
          fi

      - name: Commit changes
        run: |
          git commit -m "Update cds-typer synopsis"
      
      - name: Push changes
        run: |
          BRANCH_NAME="update-cds-typer-synopsis-$(date +'%Y%m%d%H%M%S')"
          git checkout -b "$BRANCH_NAME"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.push_changes.outputs.BRANCH_NAME }}
          title: "Automated PR: Update synopsis for cds-typer"
          body: "This PR was automatically generated and updates the output of `cds-typer --help` to the latest version."
          base: main